### ISSUE TITLE
Stealthy search bar

### ISSUE THREAD

**Issue by brotatotes** [Church-Life-Apps/Songs#124]
> Really good, brothers! Is there a way, from the home page, to search? By hymn number? Or by first line?

**Comment by brotatotes** [comment]
Unfortunate that this person wasn't able to find the search bar. We should make the search bar more obvious.

**Comment by brandonxia01** [comment]
I bet this may have been bc of an issue before where the search bar didn't render bc database didn't work on their browser. How old was the email?

Also I think I stopped getting the feedback emails forwarded to me  :(

**Comment by brotatotes** [comment]
Oh yeah I forgot about that! Yes it was probably that. I went through all the old feedback emails and this was an older one for sure.

I can forward the emails to you from my personal email. I don't remember what the email account was but forwarding is still working for me.

**Comment by 123asian** [comment]
Can you forward to me too?

**Comment by brotatotes** [comment]
Yes I'll set up forwarding for both of you.
