### ISSUE TITLE
Hymn 86

### ISSUE THREAD

**Issue by Hymnal-Feedback** [Church-Life-Apps/Songs#188]
> hi! when you are in lyric only mode, verses 5&6 disappear :( 

— Ruth

**Comment by brandonxia01** [comment]
Just checked and I think she might just needed to have scrolled down, lemme check w ruth

**Comment by brandonxia01** [comment]
Mmm ok yeah seems to be missing the verses

**Comment by brandonxia01** [comment]
I think this fixes it
https://github.com/Church-Life-Apps/Resources/pull/27
