### ISSUE TITLE
App Name

### ISSUE THREAD

**Issue by brotatotes** [Church-Life-Apps/Songs#65]
"Hymnal App" is a bit of a boring app name. Would love to have a better name. Also, there was an idea thrown around to display dynamically changing suggested verses or hymns in the top bar instead of just showing "Hymnal App". Probably warrants some further discussion for both new app name and what to display in the top bar instead of app name:

![image](https://user-images.githubusercontent.com/6797157/100191400-e4055100-2ea4-11eb-8eb0-388f84f3563c.png)

**Comment by 123asian** [comment]
Psalms, Hymns, and Spiritual Songs

**Comment by brotatotes** [comment]
Hymns and Spiritual Songs?

**Comment by brotatotes** [comment]
Going with "Songs" - short and sweet
