### ISSUE TITLE
Update Launcher Icon and splash screen icon for mobile apps

### ISSUE THREAD

**Issue by brandonxia01** [Church-Life-Apps/Songs#67]
The default app icon and splash screen when the app first opens are both the [Capacitor logo](https://bendyworks.com/assets/images/blog/2018-07-13-capacitor-elm-5c00aa6a.png). (it lowkey kind of worked because it looks a little bit like an H like "H"ymnal app lol) 

What do we want to show instead? 
* Songs and Hymns of Life logo/text (Maybe not accurate if we will accommodate multiple hymn books later)
* Create our own Logo
* Crown of thorns (as in the browser tab icon, which was originally just placeholder)
* other ideas ___

**Comment by brotatotes** [comment]
We could ask some graphic designers for help. I stole this icon from VCC graphic design:

![vcc](https://user-images.githubusercontent.com/6797157/100310192-79feb180-2f61-11eb-928f-b4ae9b29add2.png)

**Comment by brotatotes** [comment]
Should we ask someone to design a logo for us? We could ask Jocelyn, or I could ask my sister, who has done graphic design work as well?

**Comment by brandonxia01** [comment]
Since we plan on adding multiple hymnbooks, the logo can be generic, ie: not the SHL logo. 

Maybe something musical and cute?

**Comment by brotatotes** [comment]
I ended up using the VCC one for our first android app but it can be changed.

**Comment by brotatotes** [comment]
Reopening because I only updated the play store image, not the in-app splash & icon
