### ISSUE TITLE
Json schema for resources

### ISSUE THREAD

**Issue by brotatotes** [Church-Life-Apps/Songs#74]
We need to define a json schema for jsons in Resources repo. This is generally good because it forces future jsons to obey the schema. But also, this is currently making it difficult to parse lyrics since the lyrics field type in the json is undefined (cant tell if there will be v1, v2, v3, c1, c2, etc).

**Comment by brandonxia01** [comment]
I think we're good on this issue now?

**Comment by brotatotes** [comment]
This was never done, but I also am not sure if we actually need to ever do it.

What I was originally thinking is that the fact that the 'lyrics' section of the json is completely undefined is not a good thing. By undefined I mean you know it's a map, but you don't know what kinds of keys are in it, or how many. If it was well-defined, and with a json-schema file to go along with it, parsing could be less error-prone. But, maybe this is okay. We can close this because YAGNI, and address it later if it ever causes any issues.
