### ISSUE TITLE
Flaky UT

### ISSUE THREAD

**Issue by brotatotes** [Church-Life-Apps/Songs#75]
FAIL src/test/utils/SecurityUtils.test.tsx
  ● Security Utils Tests › Encrypt and Decrypt Test

    Malformed UTF-8 data

      16 |  */
      17 | export function decrypt(encryptedtext: string, privateKey: string): string {
    > 18 |   return CryptoJS.AES.decrypt(encryptedtext, privateKey).toString(CryptoJS.enc.Utf8);
         |                                                          ^
      19 | }
      20 | 

      at Object.stringify (node_modules/crypto-js/core.js:513:24)
      at WordArray.init.toString (node_modules/crypto-js/core.js:268:38)
      at decrypt (src/utils/SecurityUtils.tsx:18:58)
      at Object.it (src/test/utils/SecurityUtils.test.tsx:13:12)

PASS src/test/utils/SongUtils.test.tsx

Test Suites: 1 failed, 3 passed, 4 total
Tests:       1 failed, 12 passed, 13 total
Snapshots:   0 total
Time:        22.313 s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hymnal-app@0.0.2 run-tests: `react-scripts test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hymnal-app@0.0.2 run-tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by brandonxia01** [comment]
Closed by https://github.com/Church-Life-Apps/Songs/pull/85
