### ISSUE TITLE
Lyric View UI updates

### ISSUE THREAD

**Issue by brandonxia01** [Church-Life-Apps/Songs#76]
Some ideas on UX for lyric view:
* make the space between the individual lines smaller.
* center the text (but still left justified)

(a visual design would probably be helpful here)

Slightly out of scope enhancement:
* Settings option to adjust the font size (locally store it)

**Comment by brotatotes** [comment]
Reorganizing this incident into separate ones.

**Comment by brotatotes** [comment]
lyric view updates were done by @calebziamba !
