### ISSUE TITLE
Missing search bar bug

### ISSUE THREAD

**Issue by brotatotes** [Church-Life-Apps/Songs#91]
I've heard feedback from two people now about this and I refuse to believe it is because they simply cannot find the search bar. After thinking about it a little bit, I think the problem is there is a race condition between the database initialization and search bar rendering. Recently we modified the search bar to be hidden if the database is not initialized yet, but I think this never gets re-rendered. So the race condition is if the database initialization is slower than the search bar rendering, then the search bar will be hidden and never re-render to show itself.

Fix is to add key tag to the input element to trigger re-render when the database finishes initialization.

**Comment by brotatotes** [comment]
![image](https://user-images.githubusercontent.com/6797157/103489206-90512600-4dc7-11eb-93d4-4dd35262b835.png)

**Comment by brotatotes** [comment]
Temporary fix - refreshing page should force search bar to re-render

**Comment by brandonxia01** [comment]
Hmm, yeah I think you're right. I thought react would re-render it automatically when the db finished initializing but I just tested it and that's not the case. Hitting the "house" button re-renders it, but refreshing the page might not necessarily do it if the DB is consistently slower than the page load

Is @nubwett gonna take this one? :)

**Comment by brotatotes** [comment]
> Is @nubwett gonna take this one? :)

Yeah, he is working on it now. Yay onboarding!

**Comment by 123asian** [comment]
Ayyyy nice

**Comment by brotatotes** [comment]
If database fails to load, search bar will be missing. Currently have no plans to address this - not sure how much of a problem it really is.

Also, maybe we should make the search bar look more obvious.
