### ISSUE TITLE
# 42 some lyrics messed up

### ISSUE THREAD

**Issue by brotatotes** [Church-Life-Apps/Songs#99]
# 42 "Blessed Be Your Name": The lyric only page got some lyrics messed up. Please look into it and make the corrections needed. Thanks for your service!

**Comment by brandonxia01** [comment]
https://github.com/Church-Life-Apps/Resources/pull/11

**Comment by brotatotes** [comment]
https://github.com/Church-Life-Apps/Resources/pull/11
